[package]
name = "json_smart_formatter"
version = "0.1.0"
authors = ["rh <ryuta.hayashi@fujifilm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3.24"
failure = "0.1.6"
